---
title: "Data Hackathon Practice"
author: "Ana Hernandez, Adria Vazquez, Nataniel Tsai, Ailssa Villa, Ycied Talavera"
date: "7/24/2020"
output: pdf_document
---

**Data Inquiry**

Data from standard average (mean)

1. Far Rockaway, Little Neck & New York

2. Astoria, Brooklyn, Elmhurst, Flushing, Howard Beach, 
Jackson Heights, Jamaica, Kew Gardens & Woodhaven

3.

4.




```{r}
library(tidyverse)
library(readxl)
library(ggplot2)
library(gridExtra)

data <- read_excel("072020NYCMTAJuly2014.xlsx")

station <- names(data)

price <- c(2.750, 2.500, 2.500, 2.456, 2.435, 2.39, 2.301, 
           2.281, 2.250, 2.136, 2.131, 1.950, 1.917)
trafficMean <- rep(-1, length(data))

trafficMean[1] <- mean(na.exclude(data$HowardB))/1000
trafficMean[2] = mean(na.exclude(data$LittleNk))/1000
trafficMean[3] = mean(na.exclude(data$FRockaway))/1000
trafficMean[4] = mean(na.exclude(data$NY))/1000
trafficMean[5] = mean(na.exclude(data$Flushing))/1000
trafficMean[6] = mean(na.exclude(data$RePark))/1000
trafficMean[7] = mean(na.exclude(data$Bklyn))/1000
trafficMean[8] = mean(na.exclude(data$Astoria))/1000
trafficMean[9] = mean(na.exclude(data$KwGdns))/1000
trafficMean[10] = mean(na.exclude(data$Jamaica))/1000
trafficMean[11] = mean(na.exclude(data$JksnHts))/1000
trafficMean[12] = mean(na.exclude(data$Elmhrst))/1000
trafficMean[13] = mean(na.exclude(data$Wdhvn))/1000

tbl <- tibble(station, price, trafficMean)
```

Graph of traffic means
```{r}
ggplot(tbl, aes(x = station, y = trafficMean)) +
  geom_point(aes(color = station), size = 3) + 
  scale_shape_manual(values = seq(0,13)) + 
  labs(title = "Traffic vs. Station") +
  theme(axis.text.x = element_text(angle = 45), legend.position = "none")

```

Graph of price means
```{r}
ggplot(tbl, aes(x = station, y = price)) +
  geom_point(aes(color = station), size = 3) + 
  scale_shape_manual(values = seq(0,13)) + 
  labs(title = "Price vs. Station") +
  theme(axis.text.x = element_text(angle = 45), legend.position = "none")
  
```

```{r}
ggplot(tbl, aes(x = trafficMean, y = price)) + 
  geom_point(aes(color = station, shape = station), size = 3) + 
  scale_shape_manual(values=seq(0,13)) +
  labs(title = "Price vs. Traffic") +
  stat_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
  geom_hline(yintercept = 2.4, linetype = "dashed", color = "red") + 
  geom_hline(yintercept = 2.6, linetype = "dashed", color = "red")
```

```{r}
# Plot of traffic mean with stations at the bottom
p1 <- ggplot(tbl, aes(x = station, y = trafficMean)) +
  geom_point(aes(color = station), size = 3) + 
  scale_shape_manual(values = seq(0,13)) + 
  labs(title = "Traffic vs. Station") +
  theme(axis.text.x = element_text(angle = 45), legend.position = "none")

# Plot of price 
p2 <- ggplot(tbl, aes(x = station, y = price)) +
  geom_point(aes(color = station), size = 3) + 
  scale_shape_manual(values = seq(0,13)) + 
  labs(title = "Price vs. Station") +
  theme(axis.text.x = element_text(angle = 45), legend.position = "none")
  
grid.arrange(p1, p2, ncol = 1, nrow = 2)
```

